### ISSUE TITLE
Help me pls

### ISSUE THREAD

**Issue by Junezavr** [miatribe/GutterLines#1]
How to use ...?
Example ....
Thx

**Comment by miatribe** [comment]
It is only tested on **iRO:Odin** (iro's restart server) any other server I cant guarantee it will work, in fact I doubt it will work. This will be the case until I get time to test on other RO's clients, or someone from the other RO's submits an edit to allow the other RO's to work.

If you are on iRO:Odin then you simply run the exe from the download on the main page as **admin** (running as admin is required and the app will tell you this if you do not run as admin).

Once both the app and Ragnarok is running then you press the tiny right arrow at the bottom left of the apps window. This will cycle though all your open RO clients, do this until you have found the desired client.
