### ISSUE TITLE
How do I install this?

### ISSUE THREAD

**Issue by yoongjun** [miatribe/GutterLines#2]
Sorry if this is a dumb question, but how do I get the viewer to start running?

**Comment by miatribe** [comment]
go here https://miatribe.github.io/GutterLines/ and get the files at the download link. Then there is no installation needed just unzip the file and run it (as admin). This only works for restart iro (although I have been told it also works on iro renewal)

You can run it before or after you run ragnarok. Once ro and the gutterlines are loaded there is a little blue arrow at the bottom of the gutterlines app will cycle between your open ro clients.

**Comment by jinjinkoh19** [comment]
hoping i could use it in ROPH

**Comment by miatribe** [comment]
Due to differences in the client it will not work on ROPH. If someone were to provide the sigs for the required memory address we might be able to get it to work. But I have no plans to do that myself at this time.
